{{- range .Values.streams }}
{{- $roiEnabled := false }}
{{- if .roiStreamConfig }}
  {{- $roiEnabled = .roiStreamConfig.enabled }}
{{- else if $.Values.defaults.roiStreamConfig }}
  {{- $roiEnabled = $.Values.defaults.roiStreamConfig.enabled }}
{{- end }}
{{- if $roiEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-{{ .stream }}-roi-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: stream-{{ .stream }}
  annotations:
    {{- toYaml (default $.Values.defaults.annotations .annotations) | nindent 4 }}
data:
{{- $config := tpl (default $.Values.defaults.roiStreamConfig.config (default (dict "config" $.Values.defaults.roiStreamConfig.config) .roiStreamConfig).config) . }}
{{- range $line := splitList "\n" $config }}
{{- if and $line (ne (trim $line) "") }}
{{- $kv := splitList ":" $line }}
{{- if eq (len $kv) 2 }}
  {{ trim (index $kv 0) | replace "-" "_" | upper }}: {{ trim (index $kv 1) | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
{{- end }}