# Example for minimal configuration
streams:
  - stream: update-frame-rate-control

# Values possible for Observatory Pipelines
defaults:
  # Application identification
  appName: observatory-event-processing-app
  appVersion: 0.0.1
  clientId: observatory-ep
  
  # MongoDB connection
  mongodb:
    uri: mongodb://localhost:27017

  # ClickhouseDB connection
  clickhouse:
    uri: clickhouse:9000
    detectionRetention: 1 # hours
    movementRetention: 24 # hours
    inferenceRetention: 24 # hours
    alertRetention: 24 # hours

  # KeyDB connection
  keydb:
    uri: keydb:6379

  # MilvusDB connection
  milvus:
    uri: milvus:19530

  stream: update-frame-rate-control
  annotations:
    teknoir.org/managed-by: devstudio
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/observatory-event-processing
    tag: dev-c3f8a7c
  # Set the log level for the nvr
  # - DEBUG
  # - INFO
  # - WARNING
  # - ERROR
  debugLevel: INFO
  mqtt:
    # Local MQTT broker
    broker: mqtt.kube-system
    port: 1883
    username: "emqx_operator_controller"
    password: ""
    qos: 2
    keepAliveInterval: 10
    connectRetryInterval: 10
    # Topics
    topicSink: "events/sink"
    topicSource: "events/source"
    topicAllCameras: "camera/frames/#"
    topicDetections: "events/detections"
    topicInference: "events/inference"
    topicMovements: "events/movements"
    topicFilteredMovements: "events/filtered-movements"
    topicAlerts: "events/alerts"
    topicStaleAlerts: "toe/events/stale-alerts"
    topicSensors: "events/sensors"
    topicMeasurements: "events/measurements"
    topicToeState: "toe/state"
    topicToeEventsInference: "toe/events/inference"
    topicToeEventsMovements: "toe/events/movements"
    topicToeEventsAlerts: "toe/events/alerts"
    topicToeEventsStaleAlerts: "toe/events/stale-alerts"
    topicToeEvents: "toe/events"
    topicToeCommands: "toe/commands/framerates"
    topicToeFileCommands: "toe/commands/file"
    topicAllDevicesEvents: "/devices/+/events"
    topicFileTransfers: "/devices/+/events/file/+"
    topicDevicesEventsAlerts: "/devices/+/events/alerts"
    topicDevicesEventsStaleAlerts: "/devices/+/events/stale-alerts"
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 128Mi
  fe:
    frontEndDefaultInterval: 60 # seconds
  historian:
    apiUrl: "http://historian-api:8000"
    recordDetectionsInterval: 333 # milliseconds
    objectsToFilter: "car,truck,motorbike,person,face" # supports multiple labels via comma separated list
  regions:
    iouThreshold: 0.001 # default Intersection Over Union (IOU) threshold for object detection inside region
  video:
    directory: "/videos"
    tempDirectory: "/video-tmp"
    minStartBeforeAlert: 10 # seconds
    mountSegmentPath: false
    segmentPath: "/opt/teknoir/video/segments"
    mountClipTempPath: false
    clipTempPath: "/opt/teknoir/video/clips"
    segmentLength: 15 # seconds
    segmentRetentionLength: 5760 # segments
    maxClipLength: 600 # seconds
    clipRunupLength: 10 # seconds
    chunkMaxSize: 500000 # bytes
    chunkRetentionSeconds: 300 # seconds
    videoBasePath: "media/videos"
    hasAnnotations: true
    annotationsBucketPath: "media/annotations"
    snapshotBucketPath: "media/snapshots"
  alerts:
    staleSeconds: 30 # seconds
    personDownInterval: 10
    personDownScoreThreshold: 0.85
    personUpScoreThreshold: 0.75
    personDownUpTotalCountThreshold: 10
    loiteringLabels: "person" # supports multiple labels via comma separated list
    sensorsNodeData: "{}"
    loiteringThreshold: 60 # 60 seconds
    loiteringCountThreshold: 30
    loiteringCheckStationary: true
    loiteringStationaryThreshold: 0.01 # 1% of FOV
    safeOpenInferUniqueId: 0
    safeOpenWindowSizeSeconds: 5 # Default window size of 5 seconds
    dominantLabelsMinCount: 5
    dominantLabelsMinDuration: 5 # 5 seconds
    dominantLabelsAlertCooldownTime: 60 # 60 seconds
    motionCheckInterval: 1000 # 1 second
    motionAlertCooldownTime: 60 # 60 seconds
    alertHeatmapEnabled: true
    alertHeatmapGridSize: 20  # NXN grid size
    alertHeatmapEventsRetentionPeriod: 86400 # 24h = 86400 seconds
    alertHeatmapAlertsToFilter: "loitering,person_down" # Alerts to filter out from the heatmap, e.g. "loitering"
    alertHeatmapPercentileThreshold: 95.0 # 95% percentile
  # Deprecated and will be removed in future versions when we find a new way to handle this
  labels:
    deviceID: "test-device"
    namespace: "test-namespace"
    domain: "teknoir.cloud"
  metrics:
    interval: 60 # seconds
    port: "8000"
  transferFile:
    blockSize: 314572800 # 300MB